"""Repository rule generating the hermetic clang-cl + xwin MSVC cc toolchain.

The @msvc_cc repo holds only cheap generated files — wrapper shell scripts and
the cc_toolchain/cc_toolchain_config BUILD — so iterating on flags here never
invalidates the big @llvm_msvc_tools / @xwin_sysroot downloads (their rules
live in llvm.bzl / sysroot.bzl on purpose).

Wrappers derive every path from $0 (execroot-relative sibling repos), so they
work from Bazel actions (cwd = execroot) and from build scripts, where
rules_rust ${pwd}-expands CC/AR to absolute paths and cc-rs/cmake spawn the
tools from other working directories:

    bin/clang-cl   --target=x86_64-pc-windows-msvc, /imsvc CRT+SDK includes,
                   -msse4.1 -msse4.2 (win32-x64 baseline floor; clang-cl
                   enforces per-function target features, real MSVC does not),
                   -fuse-ld=lld-link + exported link.exe-style LIB so driver
                   links (cmake try_compile) resolve the CRT import libs.
    bin/lld-link   /libpath for CRT + SDK libs, then pass-through; rustc uses
                   it via -Clinker for the msvc linker flavor.
    bin/llvm-lib   archiver (lib.exe replacement, cc-rs AR + cmake CMAKE_AR).
    bin/llvm-rc    resource compiler (cmake finds it next to the compiler).
    bin/llvm-mt    manifest tool (cmake CMAKE_MT probe).
    bin/ml64.exe   MASM shim → llvm-ml -m64 (also bare `ml64`): cc-rs looks
    bin/ml64       up `ml64.exe` on PATH for x64 msvc .asm (blake3); the
                   blake3 crate.annotation prepends this dir to PATH.

The MSVC-flavored feature/action config (dynamic CRT /MD by default — matching
what napi/cc-rs produced under cargo-xwin; /MT only via the standard
static_link_msvcrt feature) comes from rules_cc's own
windows_cc_toolchain_config.bzl, copied into the repo exactly like
@local_config_cc does, so it always matches the resolved rules_cc version.
"""

_CLANG_CL_WRAPPER = """\
#!/bin/sh
# Generated by //bazel/toolchains/msvc:cc.bzl. clang-cl driver for
# x86_64-pc-windows-msvc against the @xwin_sysroot MSVC CRT + Windows SDK.
set -eu
execroot="$(cd "$(dirname "$0")/../../.." && pwd)"
llvm="$execroot/external/{llvm}"
splat="$execroot/external/{xwin}/splat"
# lld-link (spawned through -fuse-ld for compiler-driver links, e.g. cmake
# try_compile) resolves CRT/SDK import libs via the link.exe-style LIB env.
LIB="$splat/crt/lib/x86_64;$splat/sdk/lib/um/x86_64;$splat/sdk/lib/ucrt/x86_64"
export LIB
# -msse4.1/-msse4.2: clang-cl enforces per-function target features (real MSVC
# does not); opus' silk/x86 SSE4.1 units fail without the feature enabled
# globally. The win32-x64 addon floor is x86-64-v2 (SSE4.2 inclusive), so this
# is safe for every C dep — same flags the cargo-xwin pipeline exported.
exec "$llvm/bin/clang-cl" \\
  --target=x86_64-pc-windows-msvc \\
  -fuse-ld=lld-link \\
  -msse4.1 \\
  -msse4.2 \\
  -Wno-unused-command-line-argument \\
  "/imsvc$splat/crt/include" \\
  "/imsvc$splat/sdk/include/ucrt" \\
  "/imsvc$splat/sdk/include/um" \\
  "/imsvc$splat/sdk/include/shared" \\
  "/imsvc$splat/sdk/include/winrt" \\
  "/imsvc$splat/sdk/include/cppwinrt" \\
  "$@"
"""

_LLD_LINK_WRAPPER = """\
#!/bin/sh
# Generated by //bazel/toolchains/msvc:cc.bzl. lld-link with the @xwin_sysroot
# CRT + SDK libpaths; rustc invokes it via -Clinker (msvc linker flavor).
set -eu
execroot="$(cd "$(dirname "$0")/../../.." && pwd)"
llvm="$execroot/external/{llvm}"
splat="$execroot/external/{xwin}/splat"
# rustc addresses lld in generic multi-flavor style ("-flavor link" first);
# the single-flavor lld-link binary would treat "link" as an input file.
if [ "${{1:-}}" = "-flavor" ]; then shift 2; fi
exec "$llvm/bin/lld-link" \\
  "/libpath:$splat/crt/lib/x86_64" \\
  "/libpath:$splat/sdk/lib/um/x86_64" \\
  "/libpath:$splat/sdk/lib/ucrt/x86_64" \\
  "$@"
"""

_PASSTHROUGH_WRAPPER = """\
#!/bin/sh
# Generated by //bazel/toolchains/msvc:cc.bzl.
set -eu
execroot="$(cd "$(dirname "$0")/../../.." && pwd)"
exec "$execroot/external/{llvm}/bin/{tool}" "$@"
"""

_ML64_WRAPPER = """\
#!/bin/sh
# Generated by //bazel/toolchains/msvc:cc.bzl. MASM shim: cc-rs assembles .asm
# for x64 msvc targets (blake3's blake3_*_x86-64_windows_msvc.asm) by invoking
# `ml64.exe` from PATH on non-windows hosts; llvm-ml is a MASM-compatible
# replacement — same shim cargo-xwin installed. The blake3 crate.annotation in
# MODULE.bazel prepends this bin/ dir to the build script PATH.
set -eu
execroot="$(cd "$(dirname "$0")/../../.." && pwd)"
exec "$execroot/external/{llvm}/bin/llvm-ml" -m64 "$@"
"""

_NOP_WRAPPER = """\
#!/bin/sh
# Generated by //bazel/toolchains/msvc:cc.bzl. Placeholder for tools the MSVC
# toolchain does not have (gcov/nm/objcopy/objdump/strip).
exit 0
"""

# CMake toolchain file for the `cmake` crate (audiopus_sys' bundled opus).
# cmake's vs_link_exe helper insists on rc/mt tools for MSVC-ABI exe links
# (try_compile links a test exe), and CMake's own find_program would only look
# for `rc`/`mt` on PATH. CMAKE_CURRENT_LIST_DIR makes the file self-locating —
# no canonical repo names involved. Handed to build scripts via the
# CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc annotation env in MODULE.bazel.
_TOOLCHAIN_CMAKE = """\
# Generated by //bazel/toolchains/msvc:cc.bzl — clang-cl + lld-link + xwin
# CRT/SDK cross toolchain for x86_64-pc-windows-msvc (mirrors the toolchain
# file cargo-xwin used to generate).
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(CMAKE_C_COMPILER "${CMAKE_CURRENT_LIST_DIR}/bin/clang-cl")
set(CMAKE_CXX_COMPILER "${CMAKE_CURRENT_LIST_DIR}/bin/clang-cl")
set(CMAKE_LINKER "${CMAKE_CURRENT_LIST_DIR}/bin/lld-link")
set(CMAKE_RC_COMPILER "${CMAKE_CURRENT_LIST_DIR}/bin/llvm-rc")
set(CMAKE_MT "${CMAKE_CURRENT_LIST_DIR}/bin/llvm-mt")
# The xwin splat carries release CRT import + static libs only (msvcrt.lib /
# libcmt.lib, no debug msvcrtd.lib / libcmtd.lib — same as cargo-xwin).
# try_compile defaults to the Debug configuration, whose debug CRT the splat
# lacks; pin try_compile to Release. The shipped win32 addon statically links
# the CRT (rustc +crt-static + the static_link_msvcrt cc feature; see
# bazel/defs.bzl and crates/pi-natives/BUILD.bazel), so pin the runtime library
# to the static release CRT /MT for every config as well — otherwise CMake's
# authoritative CMAKE_MSVC_RUNTIME_LIBRARY (CMP0091 NEW) would emit /MD for the
# bundled opus objects, which then import VCRUNTIME140.dll and conflict with the
# static CRT the rest of the addon links (issue #8439). Keep this in lock-step
# with the static_link_msvcrt feature: both must select the static CRT together.
set(CMAKE_TRY_COMPILE_CONFIGURATION Release)
set(CMAKE_POLICY_DEFAULT_CMP0091 NEW)
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded)
"""

_BUILD = """\
# Generated by //bazel/toolchains/msvc:cc.bzl — hermetic clang-cl + lld-link +
# xwin CRT/SDK cc toolchain for x86_64-pc-windows-msvc. The toolchain() targets
# registering this live in //bazel/toolchains (one per supported exec host).

load("@rules_cc//cc/toolchains:cc_toolchain.bzl", "cc_toolchain")
load(":windows_cc_toolchain_config.bzl", "cc_toolchain_config")

package(default_visibility = ["//visibility:public"])

filegroup(name = "empty")

filegroup(
    name = "wrappers",
    srcs = glob(["bin/*"]) + ["toolchain.cmake"],
)

filegroup(
    name = "all_files",
    srcs = [
        ":wrappers",
        "@llvm_msvc_tools//:all",
        "@xwin_sysroot//:sysroot",
    ],
)

cc_toolchain_config(
    name = "clang_cl_xwin_config",
    abi_libc_version = "local",
    abi_version = "local",
    archiver_flags = ["/MACHINE:X64"],
    compiler = "clang-cl",
    cpu = "x64_windows",
    dbg_mode_debug_flag = "/DEBUG",
    default_link_flags = ["/MACHINE:X64"],
    fastbuild_mode_debug_flag = "/DEBUG",
    host_system_name = "local",
    msvc_cl_path = "bin/clang-cl",
    msvc_env_include = "{env_include}",
    msvc_env_lib = "{env_lib}",
    msvc_env_path = "/usr/bin:/bin",
    msvc_env_tmp = "/tmp",
    msvc_lib_path = "bin/llvm-lib",
    msvc_link_path = "bin/lld-link",
    msvc_ml_path = "bin/ml64.exe",
    supports_parse_showincludes = False,
    target_libc = "msvcrt",
    target_system_name = "x86_64-pc-windows-msvc",
    tool_paths = {{
        "ar": "bin/llvm-lib",
        "cpp": "bin/clang-cl",
        "gcc": "bin/clang-cl",
        "gcov": "bin/msvc-nop",
        "ld": "bin/lld-link",
        "ml": "bin/ml64.exe",
        "nm": "bin/msvc-nop",
        "objcopy": "bin/msvc-nop",
        "objdump": "bin/msvc-nop",
        "strip": "bin/msvc-nop",
    }},
    toolchain_identifier = "clang_cl_xwin_x64",
)

cc_toolchain(
    name = "cc_toolchain",
    all_files = ":all_files",
    ar_files = ":all_files",
    as_files = ":all_files",
    compiler_files = ":all_files",
    dwp_files = ":empty",
    linker_files = ":all_files",
    objcopy_files = ":empty",
    strip_files = ":empty",
    supports_param_files = 1,
    toolchain_config = ":clang_cl_xwin_config",
    toolchain_identifier = "clang_cl_xwin_x64",
)
"""

def _msvc_cc_impl(rctx):
    llvm = rctx.attr.llvm_repo.repo_name
    xwin = rctx.attr.xwin_repo.repo_name
    splat = "external/{}/splat".format(xwin)

    rctx.file("bin/clang-cl", _CLANG_CL_WRAPPER.format(llvm = llvm, xwin = xwin), executable = True)
    rctx.file("bin/lld-link", _LLD_LINK_WRAPPER.format(llvm = llvm, xwin = xwin), executable = True)
    for tool in ("llvm-lib", "llvm-rc", "llvm-mt"):
        rctx.file("bin/" + tool, _PASSTHROUGH_WRAPPER.format(llvm = llvm, tool = tool), executable = True)
    rctx.file("bin/msvc-nop", _NOP_WRAPPER, executable = True)
    # cc-rs resolves the x64 MASM assembler as `ml64.exe` from PATH on
    # non-windows hosts (blake3); ship both spellings of the shim.
    for name in ("ml64.exe", "ml64"):
        rctx.file("bin/" + name, _ML64_WRAPPER.format(llvm = llvm), executable = True)

    # The MSVC feature/action-config machinery, verbatim from the resolved
    # rules_cc (same mechanism @local_config_cc uses on real Windows hosts).
    rctx.template("windows_cc_toolchain_config.bzl", rctx.attr._config_bzl, executable = False)

    # CMake toolchain file for the cmake crate (no placeholders — it
    # self-locates via CMAKE_CURRENT_LIST_DIR, so no .format here).
    rctx.file("toolchain.cmake", _TOOLCHAIN_CMAKE, executable = False)

    # INCLUDE/LIB for raw cc_* compile/link actions (cwd = execroot, so the
    # execroot-relative entries resolve). The rust graph routes everything
    # through the wrappers, which pass /imsvc and /libpath themselves.
    env_include = ";".join([
        splat + "/crt/include",
        splat + "/sdk/include/ucrt",
        splat + "/sdk/include/um",
        splat + "/sdk/include/shared",
        splat + "/sdk/include/winrt",
        splat + "/sdk/include/cppwinrt",
    ])
    env_lib = ";".join([
        splat + "/crt/lib/x86_64",
        splat + "/sdk/lib/um/x86_64",
        splat + "/sdk/lib/ucrt/x86_64",
    ])
    rctx.file(
        "BUILD.bazel",
        _BUILD.format(env_include = env_include, env_lib = env_lib),
        executable = False,
    )

msvc_cc_repository = repository_rule(
    implementation = _msvc_cc_impl,
    doc = "clang-cl/lld-link wrapper scripts + MSVC-flavored cc_toolchain for x86_64-pc-windows-msvc.",
    attrs = {
        "llvm_repo": attr.label(
            default = "@llvm_msvc_tools//:BUILD.bazel",
            doc = "Anchor into the pruned LLVM tools repo (canonical name source; not fetched here).",
        ),
        "xwin_repo": attr.label(
            default = "@xwin_sysroot//:BUILD.bazel",
            doc = "Anchor into the xwin CRT/SDK sysroot repo (canonical name source; not fetched here).",
        ),
        "_config_bzl": attr.label(
            default = "@rules_cc//cc/private/toolchain:windows_cc_toolchain_config.bzl",
            doc = "rules_cc's Windows cc_toolchain_config implementation, copied into this repo.",
        ),
    },
)
